    <main>

        <div class="new-feedback">
            <p class="feedback_name feedback_h">Добавить новый отзыв:</p>
            <form id="add_feedback" class="feedback_add" method="post" action="./">
                <p>
                    <input id="name" name="name" class="validate" type="text" placeholder="Введите своё имя">
                </p>
                <p>
                    <input id="email" name="email" class="validate" placeholder="Введите email">
                </p>
                <p>
                    <textarea id="text_feedback" name="text_feedback" class="validate" placeholder="Отзыв..."></textarea>
                </p>
                <p>
                    <button id="button" name="button" type="submit">Отправить</button>
                </p>
            </form>
        </div>
    </main>